import * as burger from "./modules/burger.js"
import * as slider from "./modules/slider.js"
import * as map from "./modules/map.js"
import * as product from "./modules/products.js"
import * as form from "./modules/form.js"